name: "bart-summarize"
max_batch_size: 1
input {
  name: "text"
  data_type: TYPE_STRING
  dims: 1
}
output {
  name: "text"
  data_type: TYPE_STRING
  dims: 1
}
instance_group {
  count: 1
  kind: KIND_GPU
}
dynamic_batching {
  max_queue_delay_microseconds: 500
}
backend: "python"
