# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/concept_reference.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from clarifai.rest.grpc.proto.clarifai.api import common_pb2 as proto_dot_clarifai_dot_api_dot_common__pb2
from clarifai.rest.grpc.proto.clarifai.api.status import status_pb2 as proto_dot_clarifai_dot_api_dot_status_dot_status__pb2
from clarifai.rest.grpc.proto.clarifai.api.utils import extensions_pb2 as proto_dot_clarifai_dot_api_dot_utils_dot_extensions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/clarifai/api/concept_reference.proto',
  package='clarifai.api',
  syntax='proto3',
  serialized_pb=_b('\n*proto/clarifai/api/concept_reference.proto\x12\x0c\x63larifai.api\x1a\x1fproto/clarifai/api/common.proto\x1a&proto/clarifai/api/status/status.proto\x1a)proto/clarifai/api/utils/extensions.proto\"U\n\x10\x43onceptReference\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x11\n\tsource_id\x18\x03 \x01(\t\x12\x12\n\nsource_url\x18\x04 \x01(\t\"\x83\x01\n\x1cListConceptReferencesRequest\x12/\n\x0buser_app_id\x18\x01 \x01(\x0b\x32\x1a.clarifai.api.UserAppIDSet\x12\x12\n\nconcept_id\x18\x02 \x01(\t\x12\x0c\n\x04page\x18\x03 \x01(\r\x12\x10\n\x08per_page\x18\x04 \x01(\r\"\x88\x01\n\x1eSingleConceptReferenceResponse\x12+\n\x06status\x18\x01 \x01(\x0b\x32\x1b.clarifai.api.status.Status\x12\x39\n\x11\x63oncept_reference\x18\x02 \x01(\x0b\x32\x1e.clarifai.api.ConceptReference\"\x8e\x01\n\x1dMultiConceptReferenceResponse\x12+\n\x06status\x18\x01 \x01(\x0b\x32\x1b.clarifai.api.status.Status\x12@\n\x12\x63oncept_references\x18\x02 \x03(\x0b\x32\x1e.clarifai.api.ConceptReferenceB\x04\x80\xb5\x18\x01\x42Z\n\x1b\x63larifai2.internal.grpc.apiZ\x03\x61pi\xa2\x02\x04\x43\x41IP\xaa\x02\x16\x43larifai.Internal.GRPC\xc2\x02\x01_\xca\x02\x11\x43larifai\\Internalb\x06proto3')
  ,
  dependencies=[proto_dot_clarifai_dot_api_dot_common__pb2.DESCRIPTOR,proto_dot_clarifai_dot_api_dot_status_dot_status__pb2.DESCRIPTOR,proto_dot_clarifai_dot_api_dot_utils_dot_extensions__pb2.DESCRIPTOR,])




_CONCEPTREFERENCE = _descriptor.Descriptor(
  name='ConceptReference',
  full_name='clarifai.api.ConceptReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='clarifai.api.ConceptReference.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='clarifai.api.ConceptReference.source', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_id', full_name='clarifai.api.ConceptReference.source_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_url', full_name='clarifai.api.ConceptReference.source_url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=261,
)


_LISTCONCEPTREFERENCESREQUEST = _descriptor.Descriptor(
  name='ListConceptReferencesRequest',
  full_name='clarifai.api.ListConceptReferencesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_app_id', full_name='clarifai.api.ListConceptReferencesRequest.user_app_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='concept_id', full_name='clarifai.api.ListConceptReferencesRequest.concept_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page', full_name='clarifai.api.ListConceptReferencesRequest.page', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='per_page', full_name='clarifai.api.ListConceptReferencesRequest.per_page', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=395,
)


_SINGLECONCEPTREFERENCERESPONSE = _descriptor.Descriptor(
  name='SingleConceptReferenceResponse',
  full_name='clarifai.api.SingleConceptReferenceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='clarifai.api.SingleConceptReferenceResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='concept_reference', full_name='clarifai.api.SingleConceptReferenceResponse.concept_reference', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=398,
  serialized_end=534,
)


_MULTICONCEPTREFERENCERESPONSE = _descriptor.Descriptor(
  name='MultiConceptReferenceResponse',
  full_name='clarifai.api.MultiConceptReferenceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='clarifai.api.MultiConceptReferenceResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='concept_references', full_name='clarifai.api.MultiConceptReferenceResponse.concept_references', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\200\265\030\001')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=537,
  serialized_end=679,
)

_LISTCONCEPTREFERENCESREQUEST.fields_by_name['user_app_id'].message_type = proto_dot_clarifai_dot_api_dot_common__pb2._USERAPPIDSET
_SINGLECONCEPTREFERENCERESPONSE.fields_by_name['status'].message_type = proto_dot_clarifai_dot_api_dot_status_dot_status__pb2._STATUS
_SINGLECONCEPTREFERENCERESPONSE.fields_by_name['concept_reference'].message_type = _CONCEPTREFERENCE
_MULTICONCEPTREFERENCERESPONSE.fields_by_name['status'].message_type = proto_dot_clarifai_dot_api_dot_status_dot_status__pb2._STATUS
_MULTICONCEPTREFERENCERESPONSE.fields_by_name['concept_references'].message_type = _CONCEPTREFERENCE
DESCRIPTOR.message_types_by_name['ConceptReference'] = _CONCEPTREFERENCE
DESCRIPTOR.message_types_by_name['ListConceptReferencesRequest'] = _LISTCONCEPTREFERENCESREQUEST
DESCRIPTOR.message_types_by_name['SingleConceptReferenceResponse'] = _SINGLECONCEPTREFERENCERESPONSE
DESCRIPTOR.message_types_by_name['MultiConceptReferenceResponse'] = _MULTICONCEPTREFERENCERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConceptReference = _reflection.GeneratedProtocolMessageType('ConceptReference', (_message.Message,), dict(
  DESCRIPTOR = _CONCEPTREFERENCE,
  __module__ = 'proto.clarifai.api.concept_reference_pb2'
  # @@protoc_insertion_point(class_scope:clarifai.api.ConceptReference)
  ))
_sym_db.RegisterMessage(ConceptReference)

ListConceptReferencesRequest = _reflection.GeneratedProtocolMessageType('ListConceptReferencesRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTCONCEPTREFERENCESREQUEST,
  __module__ = 'proto.clarifai.api.concept_reference_pb2'
  # @@protoc_insertion_point(class_scope:clarifai.api.ListConceptReferencesRequest)
  ))
_sym_db.RegisterMessage(ListConceptReferencesRequest)

SingleConceptReferenceResponse = _reflection.GeneratedProtocolMessageType('SingleConceptReferenceResponse', (_message.Message,), dict(
  DESCRIPTOR = _SINGLECONCEPTREFERENCERESPONSE,
  __module__ = 'proto.clarifai.api.concept_reference_pb2'
  # @@protoc_insertion_point(class_scope:clarifai.api.SingleConceptReferenceResponse)
  ))
_sym_db.RegisterMessage(SingleConceptReferenceResponse)

MultiConceptReferenceResponse = _reflection.GeneratedProtocolMessageType('MultiConceptReferenceResponse', (_message.Message,), dict(
  DESCRIPTOR = _MULTICONCEPTREFERENCERESPONSE,
  __module__ = 'proto.clarifai.api.concept_reference_pb2'
  # @@protoc_insertion_point(class_scope:clarifai.api.MultiConceptReferenceResponse)
  ))
_sym_db.RegisterMessage(MultiConceptReferenceResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033clarifai2.internal.grpc.apiZ\003api\242\002\004CAIP\252\002\026Clarifai.Internal.GRPC\302\002\001_\312\002\021Clarifai\\Internal'))
_MULTICONCEPTREFERENCERESPONSE.fields_by_name['concept_references'].has_options = True
_MULTICONCEPTREFERENCERESPONSE.fields_by_name['concept_references']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\200\265\030\001'))
# @@protoc_insertion_point(module_scope)
