[project]
name = "clarifai-python"
version = "11.3.0" # just so we can use uv run pytest.

[tool.pytest.ini_options]
markers = ["requires_secrets: mark a test as requiring secrets to run", "coverage_only: mark a test as required to run for coverage purpose only"]
