name: "age_vit"
max_batch_size: 1
input {
  name: "image"
  data_type: TYPE_UINT8
  dims: -1
  dims: -1
  dims: 3
}
output {
  name: "softmax_predictions"
  data_type: TYPE_FP32
  dims: -1
  label_filename: "labels.txt"
}
instance_group {
  count: 1
  kind: KIND_GPU
}
dynamic_batching {
  max_queue_delay_microseconds: 500
}
backend: "python"
