# Config file for the VLLM runner
#SmolLM2-1_7B-Instruct
model:
  id: "smollm"
  user_id: "mogith-p-n"
  app_id: "test-co"
  model_type_id: "text-to-text"

build_info:
  python_version: "3.11"

inference_compute_info:
  cpu_limit: "1"
  cpu_memory: "6Gi"
  num_accelerators: 1
  accelerator_type: ["NVIDIA-*"]
  accelerator_memory: "10Gi"

checkpoints:
  type: "huggingface"
  repo_id: "HuggingFaceTB/SmolLM2-1.7B-Instruct"
  hf_token: "hf"
