name: Maintainer Tests

permissions:
    contents: read
    pull-requests: write  # Added to allow commenting on PRs

on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Run maintainer-only tests?'
        required: true
        type: boolean
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  run:
    name: Maintainer Approval Tests
    if: |
      github.event_name == 'workflow_dispatch' && github.event.inputs.run_tests == 'true' ||
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv venv
          uv pip install -r requirements.txt -r tests/requirements.txt

      - name: Set up environment
        env:
          CLARIFAI_USER_EMAIL: ${{ secrets.INTERNAL_USER_EMAIL }}
          CLARIFAI_USER_PASSWORD: ${{ secrets.INTERNAL_USER_PASSWORD }}
        run: |
          export PYTHONPATH=.
          export CLARIFAI_USER_ID="$(uv run python scripts/key_for_tests.py --get-userid)"
          export CLARIFAI_PAT="$(uv run python scripts/key_for_tests.py --create-pat)"

      - name: Run maintainer tests
        run: uv run pytest -v -m maintainer_approval --cov=. --cov-report=xml:coverage/coverage.cobertura.xml

      - name: Generate coverage report
        if: success()
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: true
          format: markdown
          output: both

      - name: Add Coverage PR Comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
