name: Run Tests - Prod

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6,18 * * *'

jobs:
  sdk-python-tests-prod:
    uses: Clarifai/clarifai-python/.github/workflows/run_tests.yml@master
    with:
      PERIODIC_CHECKS: "true"
      CLARIFAI_GRPC_BASE: "api.clarifai.com"
    secrets: inherit
